### ISSUE TITLE
Collapsible Component - Pass 1

### ISSUE THREAD

**Issue by kotAPI** [rad-ui/ui#222]
Create a Collapsible UI Component

**Comment by corners2wall** [comment]
It's look like below? If yes assign to me.
Collapsed state:
![Screenshot from 2024-01-20 00-31-37](https://github.com/rad-ui/ui/assets/110557519/5725e014-7369-455e-8906-efc06d799fc1)

Expanded state:
![Screenshot from 2024-01-20 00-31-45](https://github.com/rad-ui/ui/assets/110557519/094433c1-08a1-4d74-be40-e944fcc9e717)

**Comment by corners2wall** [comment]
Okey. Sorry for my nonsense with accordion. I understood. I wanna implement it. Assign to me please.

**Comment by corners2wall** [comment]
@kotAPI Sorry for delay. I went out of town over the weekend. I'll do it this week

**Comment by corners2wall** [comment]
@kotAPI  no problem
