### ISSUE TITLE
Issue Template for creating new issues

### ISSUE THREAD

**Issue by kotAPI** [rad-ui/ui#476]
Have important titles for respective information that is required to create a well structured issue on the repository

Bonus : Can have a section  like this
[optional] What gif best describes this PR or how it makes you feel?

Source: (Borrowed from https://github.com/open-sauced/app/pull/4178)

**Comment by GoldGroove06** [comment]
![image](https://github.com/user-attachments/assets/dd87617f-582b-4b1e-be1a-53cf37a87534)
The preview looks like this.
