### ISSUE TITLE
[New Feature] Explore Kodiak

### ISSUE THREAD

**Issue by kotAPI** [rad-ui/ui#563]
# 🚀 Feature Request

---

## **Feature Description**
 Check how we can use Kodiak to automate PRs, does it make sense for us to use this in our repo? What are the pros and cons.
 
 I've seen ShadcnUI use it, so I guess we can consider it if its helpful
 
 https://github.com/chdsbd/kodiak

**Comment by GoldGroove06** [comment]
https://github.com/marketplace/kodiakhq
There you go
