### ISSUE TITLE
[New Feature] Add Multiple direction support for Tooltip

### ISSUE THREAD

**Issue by kotAPI** [rad-ui/ui#577]
# 🚀 Feature Request

---

## **Feature Description**

Tooltip should support a prop for placement, to begin with we can add support for

#### 1. Cardinal Directions
top
bottom
left
right
#### 2. Compound Directions
For offsets or alignment toward corners:

top-left / top-start
top-right / top-end
bottom-left / bottom-start
bottom-right / bottom-end
left-top / left-start
left-bottom / left-end
right-top / right-start
right-bottom / right-end
Tip: The "start" and "end" nomenclature pairs well with bidirectional (LTR/RTL) layouts.

Shall we consider something like this?
```js
{
  position: "top",          // Places the tooltip above the target
  alignment: "start",       // Aligns the tooltip to the left
  strategy: "auto",         // Adjusts position based on viewport space
}
```

Note: We use Floating UI - If I recall correctly, most of these placements are already supported by the library 
https://floating-ui.com/docs/tooltip

**Comment by decipher-cs** [comment]
floating-ui already has a type for it, `import { Placement } from '@floating-ui/react';`
It's better to use it then [manually keeping track of all the positions](https://github.com/anihar2003/ui/commit/507cd68a9075809d7a586ce487c232386fd02baf#diff-16effa0216984e2b85590d4f120399498a550ff093bd522578ee1e2fcd86b7ddR25)
