### ISSUE TITLE
[New Feature] Feature Request Template title shouldn't be "Feature Request Template" , instead just "Feature Request"

### ISSUE THREAD

**Issue by kotAPI** [rad-ui/ui#578]
# 🚀 Feature Request

---

## **Feature Description**
As explained in the title

**Comment by krau5** [comment]
Hello @kotAPI, I assume this issue could be closed as the PR with adjustment was already merged

**Comment by krau5** [comment]
> @krau5 are you interested in picking more issues?

Yes, I am. I will have a look and drop a few comments here and there, so you could assign me somewhere
