### ISSUE TITLE
BUG: Remove random progress value for the Progress component to avoid flaky visual snapshot tests

### ISSUE THREAD

**Issue by kotAPI** [rad-ui/ui#585]
## Description

Similar to https://github.com/rad-ui/ui/issues/584
update the randomized behavior to be static always

<img width="1507" alt="image" src="https://github.com/user-attachments/assets/8a311d92-24c7-48fc-8dc0-7e86f891d453">

**Comment by krau5** [comment]
This issue should be closed as the appropriate PR (https://github.com/rad-ui/ui/pull/591) was already merged
