### ISSUE TITLE
[New Feature] `as` prop for text component 

### ISSUE THREAD

**Issue by GoldGroove06** [rad-ui/ui#605]
# 🚀 Feature Request

---

## **Feature Description**

A `as` child prop for text component like in heading component.The text right now only renders the text in p tag.
>Example: The `as` accepts `<div>`, `<span>`,` <p>` and `<label>` for rendering the text into the specified tag.
---

**Comment by krau5** [comment]
It is not really the best choice to limit "as" property to 4 tags. For instance, MUI allows you to use any tag in the "as" property. By the way, I have an example of such implementation: [link](https://github.com/krau5/react-vite-template/blob/main/src/components/Typography/index.tsx#L15)
