### ISSUE TITLE
BUG: Strong Docs - Text doesn't work well on dark mode

### ISSUE THREAD

**Issue by kotAPI** [rad-ui/ui#704]
## Description

Light Mode
<img width="1218" alt="image" src="https://github.com/user-attachments/assets/d1e77aeb-dfa8-4e0d-b420-2861109d2856" />

Dark Mode
<img width="1218" alt="image" src="https://github.com/user-attachments/assets/30660ce1-05f7-477c-b8f5-fa9f188229fd" />

Please provide:
1. A clear and concise description of what the bug is
2. Steps to reproduce the behavior
3. Expected behavior
4. Actual behavior

## Related Tickets & Documents

e.g., Relates to [#4165]

## Mobile & Desktop Screenshots/Recordings
If applicable, add screenshots/recordings that show:
- The bug in action
- Any error messages
- The expected behavior (if possible)

**Comment by GoldGroove06** [comment]
On to it . Can I get the expected output?

**Comment by GoldGroove06** [comment]
fixed in #705
